AWSTemplateFormatVersion: '2010-09-09'

Description: creates an RDS database with MYSQL engine.
  
Parameters:
  ExportVpcStackName:
    Type: String

  DBInstanceIdentifier:
    Type: String

  DBName:
    Type: String

  DBAllocatedStorage:
    Type: Number

  DBInstanceClass:
    Type: String

  MultiAZ:
    Type: String

  DBEngine:
    Type: String

  DBEngineVersion:
    Type: String

  EnvironmentName:
    Type: String
    # Default: dev

  Application:
    Type: String
    # Default: App
    Description: Define the application name
  
Resources:
  DatabasesSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-RDSPrivateSubnet1
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-RDSPrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-DatabasesubnetGroup-${Application}"

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      MasterUserPassword: '{{resolve:ssm:masterpassword:1}}'
      DBSubnetGroupName: !Ref DatabasesSubnetGroup
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: '{{resolve:ssm:masterusername:1}}'
      MultiAZ: !Ref MultiAZ
      PubliclyAccessible: false
      VPCSecurityGroups: 
         - Fn::ImportValue: !Sub ${ExportVpcStackName}-DataBaseSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-DatabaseInstance-${Application}"

  EndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dbendpoint
      Type: String
      Value: !GetAtt DatabaseInstance.Endpoint.Address
      Tier: Standard
      Description: SSM Parameter


   
    
  

